kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  name: aaron@smallnet.org
- kind: User
  name: gke-alpha-service-account@k8s-dice-magic.iam.gserviceaccount.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
rules:
- apiGroups: ["extensions",""]
  resources: ["secrets","ingresses"]
  verbs: ["patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
subjects:
- kind: ServiceAccount
  name: certbot-ksa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: certbot
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-priv-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: psp-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-user
subjects:
- kind: ServiceAccount # Omit apiGroup
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: psp-priv-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-priv-user
subjects:
- kind: ServiceAccount # Omit apiGroup
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx
- kind: ServiceAccount # Omit apiGroup
  name: redis-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: statefulset-reader
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["statefulsets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: pod-reader-rolebinding
roleRef:
  apiGroup: ""
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount # Omit apiGroup
  name: redis-serviceaccount
  namespace: default
- kind: ServiceAccount # Omit apiGroup
  name: dicemagic-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: statefulset-reader-rolebinding
roleRef:
  apiGroup: ""
  kind: Role
  name: statefulset-reader
subjects:
- kind: ServiceAccount # Omit apiGroup
  name: redis-serviceaccount
  namespace: default