apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: certbot-ksa@dicemagic-dev.iam.gserviceaccount.com
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
  namespace: default
  labels:
    app: letsencrypt
spec:
  schedule: "0 2 * * 1/3" 
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          labels:
            app: letsencrypt
        spec:
          serviceAccountName: certbot-ksa
          containers:
          - image: registry.gitlab.com/aasmall/dicemagic/letsencrypt:latest
            name: letsencrypt
            imagePullPolicy: IfNotPresent
            ports:
            - name: letsencrypt
              containerPort: 8080
            envFrom:
            - configMapRef:
                name: certbot-config
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop: ["ALL"]
          restartPolicy: Never
      backoffLimit: 0
---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: hello
# spec:
#   template:
#     # This is the pod template
#     spec:
#       serviceAccountName: certbot-ksa
#       containers:
#       - name: hello
#         image: python
#         command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
#       restartPolicy: OnFailure
#     # The pod template ends here