bases:
- ../base
- ./base
patchesStrategicMerge:
- dice-magic-app.yaml
- nginx-ingress.yaml
secretGenerator:
- name: letsencrypt-certs
  files:
  - secrets/letsencrypt-certs/tls.crt
  - secrets/letsencrypt-certs/tls.key
- name: mock-tls
  files:
  - secrets/mocks/tls.crt
  - secrets/mocks/tls.key
- name: slack-secrets
  files:
  - secrets/slack/slack-client-secret
  - secrets/slack/slack-signing-secret
- name: default-ingress-certs
  namespace: ingress-nginx
  files:
  - secrets/letsencrypt-certs/tls.crt
  - secrets/letsencrypt-certs/tls.key
generatorOptions:
  disableNameSuffixHash: true